variables:
  - name: Environment
    description: "Environment name (development, production, management, monitoring)"
    type: string
    required: true

  - name: AccountId
    description: "AWS Account ID for this environment"
    type: string
    required: true

  - name: AccountEmail
    description: "Email associated with this AWS account"
    type: string
    required: true

  - name: ProjectName
    description: "Project name passed from parent template"
    type: string
    required: true

  - name: CreateEuWest1
    description: "Create eu-west-1 region configuration"
    type: bool
    default: true

  - name: CreateUsEast1
    description: "Create us-east-1 region configuration"
    type: bool
    default: false

  - name: CreateApSoutheast1
    description: "Create ap-southeast-1 region configuration"
    type: bool
    default: false

dependencies:
  - name: eu-west-1-region
    template-url: "./region-template"
    output-folder: "eu-west-1"
    variables:
      Region: "eu-west-1"
      Environment: "{{.Environment}}"
      ProjectName: "{{.ProjectName}}"
      CreateVpcStack: '{{eq .Environment "development"}}'
    skip: "{{not .CreateEuWest1}}"

  - name: us-east-1-region
    template-url: "./region-template"
    output-folder: "us-east-1"
    variables:
      Region: "us-east-1"
      Environment: "{{.Environment}}"
      ProjectName: "{{.ProjectName}}"
      CreateVpcStack: false
    skip: "{{not .CreateUsEast1}}"

  - name: ap-southeast-1-region
    template-url: "./region-template"
    output-folder: "ap-southeast-1"
    variables:
      Region: "ap-southeast-1"
      Environment: "{{.Environment}}"
      ProjectName: "{{.ProjectName}}"
      CreateVpcStack: false
    skip: "{{not .CreateApSoutheast1}}"

skip_files:
  - path: "eu-west-1"
    condition: "{{not .CreateEuWest1}}"
  - path: "us-east-1"
    condition: "{{not .CreateUsEast1}}"
  - path: "ap-southeast-1"
    condition: "{{not .CreateApSoutheast1}}"
